"""add release year floor

Revision ID: 0617cf9ec6a2
Revises: 9e6572abbb88
Create Date: 2026-09-06 23:39:12.884538

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0617cf9ec6a2'
down_revision: str | Sequence[str] | None = '9e6572abbb88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_requests', sa.Column('min_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decision_requests', 'min_year')
    # ### end Alembic commands ###
