"""initial schema

Revision ID: 9e6572abbb88
Revises: 
Create Date: 2026-09-04 17:46:05.315442

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9e6572abbb88'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('tmdb_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('original_title', sa.Text(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('vote_average', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('poster_path', sa.Text(), nullable=True),
    sa.Column('backdrop_path', sa.Text(), nullable=True),
    sa.Column('original_language', sa.String(length=16), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=False),
    sa.Column('details_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_index('ix_movies_rating', 'movies', ['vote_average', 'vote_count'], unique=False)
    op.create_index('ix_movies_runtime', 'movies', ['runtime_minutes'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('provider_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('genre_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('max_runtime', sa.Integer(), nullable=False),
    sa.Column('min_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('region', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_requests_session', 'decision_requests', ['session_id', 'created_at'], unique=False)
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.tmdb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_index('ix_movie_genres_genre', 'movie_genres', ['genre_id'], unique=False)
    op.create_table('movie_providers',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=2), nullable=False),
    sa.Column('monetization_type', sa.Text(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.tmdb_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'provider_id', 'region', 'monetization_type')
    )
    op.create_index('ix_movie_providers_lookup', 'movie_providers', ['provider_id', 'region', 'monetization_type'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.SmallInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('band_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.tmdb_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['decision_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_movie', 'recommendations', ['movie_id'], unique=False)
    op.create_index('uq_recommendations_attempt', 'recommendations', ['request_id', 'attempt'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('accepted', 'rejected', name='feedback_action'), nullable=False),
    sa.Column('reason', sa.Enum('already_seen', 'not_in_the_mood', 'too_long', 'wrong_genre', 'looks_bad', 'other', name='reject_reason'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(action = 'rejected') = (reason IS NOT NULL)", name='ck_feedback_reason_iff_rejected'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.tmdb_id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id')
    )
    op.create_index('ix_feedback_session_movie', 'feedback', ['session_id', 'movie_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_session_movie', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('uq_recommendations_attempt', table_name='recommendations')
    op.drop_index('ix_recommendations_movie', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_movie_providers_lookup', table_name='movie_providers')
    op.drop_table('movie_providers')
    op.drop_index('ix_movie_genres_genre', table_name='movie_genres')
    op.drop_table('movie_genres')
    op.drop_index('ix_decision_requests_session', table_name='decision_requests')
    op.drop_table('decision_requests')
    op.drop_table('sessions')
    op.drop_table('providers')
    op.drop_index('ix_movies_runtime', table_name='movies')
    op.drop_index('ix_movies_rating', table_name='movies')
    op.drop_table('movies')
    op.drop_table('genres')
    # ### end Alembic commands ###
